name: myad
main: com.piggest.minecraft.bukkit.myad.Myad
api-version: 1.13
version: 0.1.0
author: Pentyum
commands:
  myad:
    description: myad
    usage: /<command> apply <cycle[h|m]> <times> <contents> to apply ad.
    permission: myad.apply
    permission-message: You don't have permission
permissions:
  myad.*:
    description: Gives access to all myad commands
    default: op
  myad.apply:
    description: Gives access to apply ad
    default: true
  myad.changeprice:
    description: change ad price
    default: op
  myad.free:
    description: free ad
    default: op
  myad.modify:
    description: modify applied ad
    default: true
  myad.info:
    description: look up my ad info
    default: true
  myad.info.others:
    description: look up others ad info
    default: op
  myad.list:
    description: list ad info
    default: op
softdepend: [Vault]