name: myad
main: com.piggest.minecraft.bukkit.myad.Myad
api-version: 1.13
version: 0.0.1
author: Pentyum
commands:
  myad:
    description: myad
    usage: /<command> apply <cycle(h)> <times> <contents> to apply ad.
    permission: myad.apply
    permission-message: You don't have permission
permissions:
  myad.*:
    description: Gives access to all myad commands
    default: op
  myad.apply:
    description: Gives access to apply ad
    default: true
  myad.changeprice:
    description: change ad price
    default: op
  myad.free:
    description: free ad
    default: op
softdepend: [Vault]